CREATE TABLE IF NOT EXISTS research_jobs (
  id TEXT PRIMARY KEY, gs_id TEXT NOT NULL DEFAULT '', title TEXT NOT NULL, query TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued', requested_by TEXT NOT NULL, input_json TEXT NOT NULL DEFAULT '{}',
  result_json TEXT NOT NULL DEFAULT '{}', error_code TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS research_evidence (
  id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,
  source_url TEXT NOT NULL DEFAULT '', title TEXT NOT NULL DEFAULT '', excerpt TEXT NOT NULL DEFAULT '',
  score INTEGER NOT NULL DEFAULT 0, retrieved_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
