"use client";

import { type FormEvent, useEffect, useState } from "react";
type Job = { id: string; title: string; query: string; gsId: string; status: string };

export default function ResearchWorkspacePage() {
  const [jobs, setJobs] = useState<Job[]>([]); const [title, setTitle] = useState(""); const [query, setQuery] = useState(""); const [gsId, setGsId] = useState(""); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/research/jobs"); const body = await response.json(); if (response.ok) setJobs(body.jobs ?? []); else setMessage(body.error ?? "Unable to load research jobs."); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage("Starting retrieval…"); const response = await fetch("/api/admin/research/jobs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title, query, gsId }) }); const body = await response.json(); setMessage(response.ok ? body.status === "needs_configuration" ? "Job saved. Configure the AI Search binding and instance before retrieval can run." : "Evidence retrieved. Review citations before drafting." : body.error ?? "Unable to start research."); if (response.ok) { setTitle(""); setQuery(""); setGsId(""); await load(); } }
  return <main className="mx-auto max-w-5xl space-y-8 px-4 py-10"><header><p className="text-sm uppercase tracking-[0.2em] text-slate-500">Operator</p><h1 className="text-3xl font-semibold">Research workspace</h1><p className="mt-2 text-slate-600">Retrieval returns reviewable evidence only. It cannot publish, list, email, or alter canonical object facts.</p></header><form onSubmit={submit} className="grid gap-4 border p-5"><label className="grid gap-1">Object / research title<input required value={title} onChange={(event) => setTitle(event.target.value)} className="border p-2" /></label><label className="grid gap-1">Canonical gs_id (optional)<input value={gsId} onChange={(event) => setGsId(event.target.value)} className="border p-2" /></label><label className="grid gap-1">Research question<textarea required value={query} onChange={(event) => setQuery(event.target.value)} className="min-h-24 border p-2" /></label><button className="w-fit bg-slate-950 px-4 py-2 text-white">Retrieve evidence</button></form>{message ? <p role="status">{message}</p> : null}<section><h2 className="text-xl font-semibold">Recent jobs</h2><div className="mt-3 grid gap-3">{jobs.map((job) => <article key={job.id} className="border p-4"><div className="flex justify-between gap-4"><strong>{job.title}</strong><span>{job.status.replaceAll("_", " ")}</span></div><p className="mt-2 text-slate-600">{job.query}</p>{job.gsId ? <p className="mt-2 text-sm">gs_id: {job.gsId}</p> : null}</article>)}{jobs.length === 0 ? <p className="text-slate-600">No research jobs yet.</p> : null}</div></section></main>;
}
